#  IF NEITHER REGIONS OR WORLDS ARE ENABLED, BOUNTIES CAN BE CLAIMED ANYWHERE.
regions:
  # If this option is enabled, The plugin will consider a kill only if its in one of the listed worldguard regions.
  use: false
  list:
    - warzone
    - warzone2
worlds:
  # If this option is enabled, The plugin will consider a kill only if its in one of the listed worlds.
  use: false
  list:
    - world
    - world_the_end

bounties:
  # How many bounties can a player place at the same time.
  max: 2
  # How much does a bounty last for (in seconds)
  expiry: 259200
  # Specify how much from the bounty does the sever take. (percent)
  # Set it to 0 so the player that kills the target gets 100% of the bounty.
  tax: 5

# GUIs SETTINGS
menu:
  title: '&cBounties'
  items:
    filler:
      material: 'BLACK_STAINED_GLASS_PANE'
      name: ' '
      lore: []
    next-page:
      material: 'PAPER'
      name: '&6Next'
      lore: []
    previous-page:
      material: 'PAPER'
      name: '&6Previous'
      lore: []
    # Local placeholders: %payer%, %amount%, %bountyId%, %expiryTime%
    bounty:
      name: '&5Target: &c%player_name%'
      lore:
        - ''
        - '&ePayer: &6%payer%'
        - '&eBounty: &6%amount%$'
        - '&eID: &6%bountyId%'
        - '&eExpires in: &6%expiryTime%'

# If this option is enabled, debug messages will be sent in console.
debug: false