name: BountySystem
version: @version@
author: BlitzOffline
main: com.blitzoffline.bountysystem.BountySystem
website: github.com/BlitzOffline
api-version: 1.13
softdepend: [PlaceholderAPI, Vault, WorldGuard]