name: BountySystem
version: @version@
author: BlitzOffline
website: github.com/BlitzOffline

api-version: 1.16
softdepend: [WorldGuard]
depend: [PlaceholderAPI, Vault]
main: com.blitzoffline.bountysystem.BountySystem